### ISSUE TITLE
Passbolt

### ISSUE THREAD

**Issue by tavoda** [cnieg/helm-charts#70]
Hello, how to use passbolt helm chart? There is no EMAIL configuration and I don't know how to use without this? Am I missing something?

**Comment by Thomah** [comment]
Hello tavoda,

If you need to provide email configuration to the chart, you can override environment variables in the values like this :

```yaml
env:
  PASSBOLT_EMAIL_SHOW_SECRET: false
  PASSBOLT_EMAIL_SHOW_URI: false
  PASSBOLT_EMAIL_SHOW_USERNAME: false
  PASSBOLT_EMAIL_SEND_PASSWORD_CREATE: false
  PASSBOLT_EMAIL_SEND_PASSWORD_UPDATE: false
  # PASSBOLT_REGISTRATION_PUBLIC: true
  # EMAIL_DEFAULT_FROM: noreply@example.com
  # EMAIL_TRANSPORT_DEFAULT_HOST: smtp.example.com
  # EMAIL_TRANSPORT_DEFAULT_PORT: 25
  # EMAIL_TRANSPORT_DEFAULT_TIMEOUT: 30
```

You can also provide other configuration via this mechanism like environment variables listed on the Passbolt website : https://help.passbolt.com/configure/environment/reference

After startup of the main pod, you need to manually create the first administrator with the following command inside the container :

```bash
bin/cake passbolt register_user -u <email> -f <firstname> -l <lastname> -r admin
```

Then, follow the instructions printed on screen.

Hope this helps,
Thomah
